// Circuits type definitions generated by Midnight Compact Compiler for zkpass.compact
import type { Witnesses } from '../witnesses';

export interface PureCircuits {
  computeCommitment(secret: Uint8Array | string, salt: Uint8Array | string): string;
  calculateMerkleRoot(leaf: Uint8Array | string, path: Array<Uint8Array | string>, index: number | bigint): string;
}

export interface ImpureCircuits<T = any> {
  verifyCredentialProof(
    context: { ledger: any; witnesses: Witnesses<T> },
    accessContextHash: Uint8Array | string
  ): { isValid: boolean; proofHash: string };
  registerCredentialRoot(
    context: { ledger: any },
    newRoot: Uint8Array | string,
    adminSignatureWitness: Uint8Array | string
  ): void;
}

export declare const pureCircuits: PureCircuits;
