// Witnesses type definitions generated by Midnight Compact Compiler for zkpass.compact
export type Witnesses<T = any> = {
  secretCredential: (context: T) => Uint8Array | string;
  credentialSalt: (context: T) => Uint8Array | string;
  merklePath: (context: T) => Array<Uint8Array | string>;
  leafIndex: (context: T) => number | bigint;
  adminSignatureWitness?: (context: T) => Uint8Array | string;
};

export declare function createWitnessContext<T>(witnesses: Witnesses<T>): Witnesses<T>;
