// Contract type definitions generated by Midnight Compact Compiler for zkpass.compact
import type { Witnesses } from '../witnesses';
import type { PureCircuits, ImpureCircuits } from '../circuits';

export interface Ledger {
  readonly credentialRoot: string;
  readonly accessGrantedCount: bigint;
  readonly adminPublicKeyHash: string;
  readonly revocationRoot: string;
}

export declare const initialLedgerState: (adminKeyHash?: string, initialRoot?: string) => Ledger;

export declare class Contract<T = any, W extends Witnesses<T> = Witnesses<T>> {
  readonly witnesses: W;
  readonly circuits: PureCircuits & ImpureCircuits<T>;
  readonly initialLedgerState: Ledger;

  constructor(witnesses: W);

  initialState(context: T): {
    currentLedgerState: Ledger;
  };
}

export declare function ledger(state: { currentLedgerState: Ledger } | Ledger): Ledger;
export declare const pureCircuits: PureCircuits;
export declare const contract: Contract<any>;
